pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
	        echo 'Build initiated....'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
    }
}
