pipeline {
    agent any
    tools {
        maven 'maven 3.9.9'
        jdk 'java 1.7'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing ..'
                sh 'mvn test'
            }
        }
        
    }
}
